### ISSUE TITLE
[setting] 초기 설정

### ISSUE THREAD

**Issue by wongbingg** [apwierk2451/GifTogether#1]
## Description
프로젝트 초기 구조 설계

## TODO
- [x] Gifticon 모델 생성
- [x] UseInfo 모델 생성
- [x] 기본 파일, 그룹 생성

**Comment by wongbingg** [comment]
초기세팅 완료
