### ISSUE TITLE
[refactor] 기능수정  

### ISSUE THREAD

**Issue by wongbingg** [apwierk2451/GifTogether#15]
## Description
프로젝트 진행 중 기능을 수정합니다.

## TODO
- [x] 회원탈퇴기능 추가
- [x] LoginScene Toast 애니메이션 추가
- [x] MyPage 로그아웃, 탈퇴 Alert 추가 
---
- [x] 탭바 아이템 중복 탭시, 탭 refresh 적용
- [x] 마이페이지 내 판매목록 깜빡임 현상 해결

**Comment by wongbingg** [comment]
추가 기능수정으로 인한 이슈 재오픈
