### ISSUE TITLE
[feat] 검색화면

### ISSUE THREAD

**Issue by wongbingg** [apwierk2451/GifTogether#19]
## Description
검색 탭을 구현합니다.
## TODO
- [x] 검색화면 구현
- [x] 최근 검색어 저장 (CoreData)
- [x] 최근 검색어 History 삭제
- [x] 최근 검색 순으로 정렬하여 maxCount 까지 표시
