### ISSUE TITLE
[refactor] MyPageScene

### ISSUE THREAD

**Issue by wongbingg** [apwierk2451/GifTogether#25]
## Description

MyPageScene 에서 내 판매목록을 볼 수 있도록 수정합니다. 

## TODO
- [x] UserInfo 모델에서 판매목록값을 가지는 salesList 프로퍼티 추가
- [x] 기프티콘 등록작업이 일어날 때<RegisterGifticonUseCase>, UserInfo.salesList 배열에 기프티콘의 uuid를 append 
- [x] MyPage에서 UserInfo.salesList 정보를 표현
