### ISSUE TITLE
[feat] 상세화면 

### ISSUE THREAD

**Issue by apwierk2451** [apwierk2451/GifTogether#7]
## Description
상세 화면을 구현합니다.
## TODO
- [x] 네비게이션 바 구현
- [x] 상품 이미지 구현
- [x] 상품 설명 뷰 구현
- [x] 상품 추천 뷰 구현
- [x] 구매 버튼 및 찜 버튼 고정 구현
